package es.rutolo.martillodeguerra;

import java.util.HashMap;

//Implementa el patrón de diseño Singleton
public class Diccionario {
    private static Diccionario instancia = null;

    private HashMap<NomTal,Talento> talentos;
    private HashMap<NomHab,Habilidad> habilidades;
    private HashMap<NomProf,Profesion> profesiones;

    public Diccionario(){
        talentos = new HashMap<>();
        talentos.put(NomTal.A_CORRER,new Talento(NomTal.A_CORRER));
        talentos.put(NomTal.AFINIDAD_AETHYR,new Talento(NomTal.AFINIDAD_AETHYR));
        talentos.put(NomTal.AMBIDIESTRO,new Talento(NomTal.AMBIDIESTRO));
        talentos.put(NomTal.AMENAZADOR,new Talento(NomTal.AMENAZADOR));
        talentos.put(NomTal.ARMAS_NATURALES,new Talento(NomTal.ARMAS_NATURALES));
        talentos.put(NomTal.ARTESANIA_ENANA,new Talento(NomTal.ARTESANIA_ENANA));
        talentos.put(NomTal.ATERRADOR,new Talento(NomTal.ATERRADOR));
        talentos.put(NomTal.AUDAZ,new Talento(NomTal.AUDAZ));
        talentos.put(NomTal.BRIOSO,new Talento(NomTal.BRIOSO));
        talentos.put(NomTal.CALLEJEO,new Talento(NomTal.CALLEJEO));
        talentos.put(NomTal.CERTERO,new Talento(NomTal.CERTERO));
        talentos.put(NomTal.CIRUGIA,new Talento(NomTal.CIRUGIA));
        talentos.put(NomTal.CONTORSIONISTA,new Talento(NomTal.CONTORSIONISTA));
        talentos.put(NomTal.CORTES,new Talento(NomTal.CORTES));
        talentos.put(NomTal.DESARMAR,new Talento(NomTal.DESARMAR));
        talentos.put(NomTal.DESENVAINADO_RAPIDO,new Talento(NomTal.DESENVAINADO_RAPIDO));
        talentos.put(NomTal.DISPARO_CERTERO,new Talento(NomTal.DISPARO_CERTERO));
        talentos.put(NomTal.DISPARO_INFALIBLE,new Talento(NomTal.DISPARO_INFALIBLE));
        talentos.put(NomTal.DON_GENTES,new Talento(NomTal.DON_GENTES));
        talentos.put(NomTal.DOTES_ARTISTICAS,new Talento(NomTal.DOTES_ARTISTICAS));
        talentos.put(NomTal.EQUITACION_ACROBATICA,new Talento(NomTal.EQUITACION_ACROBATICA));
        talentos.put(NomTal.ERRANTE,new Talento(NomTal.ERRANTE));
        talentos.put(NomTal.ESPECIALISTA_ARMAS,new Talento(NomTal.ESPECIALISTA_ARMAS));
        talentos.put(NomTal.ETIQUETA,new Talento(NomTal.ETIQUETA));
        talentos.put(NomTal.EXPERTO_TRAMPAS,new Talento(NomTal.EXPERTO_TRAMPAS));
        talentos.put(NomTal.FRENESI,new Talento(NomTal.FRENESI));
        talentos.put(NomTal.GATO_CALLEJERO,new Talento(NomTal.GATO_CALLEJERO));
        talentos.put(NomTal.GENIO_ARITMETICO,new Talento(NomTal.GENIO_ARITMETICO));
        talentos.put(NomTal.GOLPE_CONMOCIONADOR,new Talento(NomTal.GOLPE_CONMOCIONADOR));
        talentos.put(NomTal.GOLPE_LETAL,new Talento(NomTal.GOLPE_LETAL));
        talentos.put(NomTal.GOLPE_PODEROSO,new Talento(NomTal.GOLPE_PODEROSO));
        talentos.put(NomTal.GUERRERO_NATO,new Talento(NomTal.GUERRERO_NATO));
        talentos.put(NomTal.HECHIZOS_ARMADURA,new Talento(NomTal.HECHIZOS_ARMADURA));
        talentos.put(NomTal.IMITADOR,new Talento(NomTal.IMITADOR));
        talentos.put(NomTal.IMPERTURBABLE,new Talento(NomTal.IMPERTURBABLE));
        talentos.put(NomTal.INQUIETANTE,new Talento(NomTal.INQUIETANTE));
        talentos.put(NomTal.INTELECTUAL,new Talento(NomTal.INTELECTUAL));
        talentos.put(NomTal.INTREPIDO,new Talento(NomTal.INTREPIDO));
        talentos.put(NomTal.INTRIGANTE,new Talento(NomTal.INTRIGANTE));
        talentos.put(NomTal.LEVITACION,new Talento(NomTal.LEVITACION));
        talentos.put(NomTal.LINGUISTICA,new Talento(NomTal.LINGUISTICA));
        talentos.put(NomTal.LUCHA,new Talento(NomTal.LUCHA));
        talentos.put(NomTal.MAGIA_MENOR,new Talento(NomTal.MAGIA_MENOR));
        talentos.put(NomTal.MAGIA_OSCURA,new Talento(NomTal.MAGIA_OSCURA));
        talentos.put(NomTal.MAGIA_PUERIL,new Talento(NomTal.MAGIA_PUERIL));
        talentos.put(NomTal.MAGIA_VULGAR,new Talento(NomTal.MAGIA_VULGAR));
        talentos.put(NomTal.MANOS_RAPIDAS,new Talento(NomTal.MANOS_RAPIDAS));
        talentos.put(NomTal.MEDITACION,new Talento(NomTal.MEDITACION));
        talentos.put(NomTal.MUY_FUERTE,new Talento(NomTal.MUY_FUERTE));
        talentos.put(NomTal.MUY_RESISTENTE,new Talento(NomTal.MUY_RESISTENTE));
        talentos.put(NomTal.NEGOCIADOR,new Talento(NomTal.NEGOCIADOR));
        talentos.put(NomTal.NO_MUERTO,new Talento(NomTal.NO_MUERTO));
        talentos.put(NomTal.ODIO_VISCERAL,new Talento(NomTal.ODIO_VISCERAL));
        talentos.put(NomTal.OIDO_AGUZADO,new Talento(NomTal.OIDO_AGUZADO));
        talentos.put(NomTal.ORADOR_EXPERTO,new Talento(NomTal.ORADOR_EXPERTO));
        talentos.put(NomTal.ORIENTACION,new Talento(NomTal.ORIENTACION));
        talentos.put(NomTal.PARADA_VELOZ,new Talento(NomTal.PARADA_VELOZ));
        talentos.put(NomTal.PELEA_CALLEJERA,new Talento(NomTal.PELEA_CALLEJERA));
        talentos.put(NomTal.PERICIA_SUBTERRANEA,new Talento(NomTal.PERICIA_SUBTERRANEA));
        talentos.put(NomTal.PIES_LIGEROS,new Talento(NomTal.PIES_LIGEROS));
        talentos.put(NomTal.PISTOLERO_EXPERTO,new Talento(NomTal.PISTOLERO_EXPERTO));
        talentos.put(NomTal.PROYECTIL_INFALIBLE,new Talento(NomTal.PROYECTIL_INFALIBLE));
        talentos.put(NomTal.PUNTERIA,new Talento(NomTal.PUNTERIA));
        talentos.put(NomTal.RECARGA_RAPIDA,new Talento(NomTal.RECARGA_RAPIDA));
        talentos.put(NomTal.RECIO,new Talento(NomTal.RECIO));
        talentos.put(NomTal.REFLEJOS_RAPIDOS,new Talento(NomTal.REFLEJOS_RAPIDOS));
        talentos.put(NomTal.RESISTENCIA_CAOS,new Talento(NomTal.RESISTENCIA_CAOS));
        talentos.put(NomTal.RESISTENCIA_ENFERMEDADES,new Talento(NomTal.RESISTENCIA_ENFERMEDADES));
        talentos.put(NomTal.RESISTENCIA_MAGIA,new Talento(NomTal.RESISTENCIA_MAGIA));
        talentos.put(NomTal.RESISTENCIA_VENENOS,new Talento(NomTal.RESISTENCIA_VENENOS));
        talentos.put(NomTal.ROBUSTO,new Talento(NomTal.ROBUSTO));
        talentos.put(NomTal.SABER_ARCANO,new Talento(NomTal.SABER_ARCANO));
        talentos.put(NomTal.SABER_DIVINO,new Talento(NomTal.SABER_DIVINO));
        talentos.put(NomTal.SABER_OSCURO,new Talento(NomTal.SABER_OSCURO));
        talentos.put(NomTal.SANGRE_FRIA,new Talento(NomTal.SANGRE_FRIA));
        talentos.put(NomTal.SENTIDOS_DESARROLLADOS,new Talento(NomTal.SENTIDOS_DESARROLLADOS));
        talentos.put(NomTal.SEXTO_SENTIDO,new Talento(NomTal.SEXTO_SENTIDO));
        talentos.put(NomTal.SUERTE,new Talento(NomTal.SUERTE));
        talentos.put(NomTal.TEMIBLE,new Talento(NomTal.TEMIBLE));
        talentos.put(NomTal.VIAJERO_CURTIDO,new Talento(NomTal.VIAJERO_CURTIDO));
        talentos.put(NomTal.VISION_NOCTURNA,new Talento(NomTal.VISION_NOCTURNA));
        talentos.put(NomTal.VISTA_EXCELENTE,new Talento(NomTal.VISTA_EXCELENTE));
        talentos.put(NomTal.VOLADOR,new Talento(NomTal.VOLADOR));

        habilidades = new HashMap<>();
        habilidades.put(NomHab.ACTUAR,new Habilidad(NomHab.ACTUAR));
        habilidades.put(NomHab.ADIESTRAR_ANIMALES,new Habilidad(NomHab.ADIESTRAR_ANIMALES));
        habilidades.put(NomHab.BUSCAR,new Habilidad(NomHab.BUSCAR));
        habilidades.put(NomHab.CARISMA,new Habilidad(NomHab.CARISMA));
        habilidades.put(NomHab.CARISMA_ANIMAL,new Habilidad(NomHab.CARISMA_ANIMAL));
        habilidades.put(NomHab.CANALIZACION,new Habilidad(NomHab.CANALIZACION));
        habilidades.put(NomHab.CHARLATANERIA,new Habilidad(NomHab.CHARLATANERIA));
        habilidades.put(NomHab.CODIGO_SECRETO,new Habilidad(NomHab.CODIGO_SECRETO));
        habilidades.put(NomHab.CONDUCIR,new Habilidad(NomHab.CONDUCIR));
        habilidades.put(NomHab.CONSUMIR_ALCOHOL,new Habilidad(NomHab.CONSUMIR_ALCOHOL));
        habilidades.put(NomHab.COTILLEO,new Habilidad(NomHab.COTILLEO));
        habilidades.put(NomHab.CRIAR_ANIMALES,new Habilidad(NomHab.CRIAR_ANIMALES));
        habilidades.put(NomHab.DISFRAZ,new Habilidad(NomHab.DISFRAZ));
        habilidades.put(NomHab.ESCALAR,new Habilidad(NomHab.ESCALAR));
        habilidades.put(NomHab.ESCONDERSE,new Habilidad(NomHab.ESCONDERSE));
        habilidades.put(NomHab.ESQUIVAR,new Habilidad(NomHab.ESQUIVAR));
        habilidades.put(NomHab.FORZAR_CERRADURAS,new Habilidad(NomHab.FORZAR_CERRADURAS));
        habilidades.put(NomHab.HABLAR_IDIOMA,new Habilidad(NomHab.HABLAR_IDIOMA));
        habilidades.put(NomHab.HIPNOTISMO,new Habilidad(NomHab.HIPNOTISMO));
        habilidades.put(NomHab.INTIMIDAR,new Habilidad(NomHab.INTIMIDAR));
        habilidades.put(NomHab.JUGAR,new Habilidad(NomHab.JUGAR));
        habilidades.put(NomHab.LEER_ESCRIBIR,new Habilidad(NomHab.LEER_ESCRIBIR));
        habilidades.put(NomHab.LEER_LABIOS,new Habilidad(NomHab.LEER_LABIOS));
        habilidades.put(NomHab.LENGUA_ARCANA,new Habilidad(NomHab.LENGUA_ARCANA));
        habilidades.put(NomHab.LENGUA_SECRETA,new Habilidad(NomHab.LENGUA_SECRETA));
        habilidades.put(NomHab.MANDO,new Habilidad(NomHab.MANDO));
        habilidades.put(NomHab.MONTAR,new Habilidad(NomHab.MONTAR));
        habilidades.put(NomHab.MOVIMIENTO_SILENCIOSO,new Habilidad(NomHab.MOVIMIENTO_SILENCIOSO));
        habilidades.put(NomHab.NADAR,new Habilidad(NomHab.NADAR));
        habilidades.put(NomHab.NAVEGAR,new Habilidad(NomHab.NAVEGAR));
        habilidades.put(NomHab.OFICIO,new Habilidad(NomHab.OFICIO));
        habilidades.put(NomHab.ORIENTACION,new Habilidad(NomHab.ORIENTACION));
        habilidades.put(NomHab.PERCEPCION,new Habilidad(NomHab.PERCEPCION));
        habilidades.put(NomHab.PONER_TRAMPAS,new Habilidad(NomHab.PONER_TRAMPAS));
        habilidades.put(NomHab.PREPARAR_VENENOS,new Habilidad(NomHab.PREPARAR_VENENOS));
        habilidades.put(NomHab.PRESTIDIGITACION,new Habilidad(NomHab.PRESTIDIGITACION));
        habilidades.put(NomHab.RASTREAR,new Habilidad(NomHab.RASTREAR));
        habilidades.put(NomHab.REGATEAR,new Habilidad(NomHab.REGATEAR));
        habilidades.put(NomHab.REMAR,new Habilidad(NomHab.REMAR));
        habilidades.put(NomHab.SABIDURIA_ACADEMICA,new Habilidad(NomHab.SABIDURIA_ACADEMICA));
        habilidades.put(NomHab.SABIDURIA_POPULAR,new Habilidad(NomHab.SABIDURIA_POPULAR));
        habilidades.put(NomHab.SANAR,new Habilidad(NomHab.SANAR));
        habilidades.put(NomHab.SEGUIMIENTO,new Habilidad(NomHab.SEGUIMIENTO));
        habilidades.put(NomHab.SENTIR_MAGIA,new Habilidad(NomHab.SENTIR_MAGIA));
        habilidades.put(NomHab.SUPERVIVENCIA,new Habilidad(NomHab.SUPERVIVENCIA));
        habilidades.put(NomHab.TASAR,new Habilidad(NomHab.TASAR));
        habilidades.put(NomHab.TORTURA,new Habilidad(NomHab.TORTURA));
        habilidades.put(NomHab.VENTRILOQUIA,new Habilidad(NomHab.VENTRILOQUIA));
        
        profesiones = new HashMap<>();
        profesiones.put(NomProf.ALBOROTADOR,new Profesion(NomProf.ALBOROTADOR));
        profesiones.put(NomProf.APRENDIZ_HECHICERO,new Profesion(NomProf.APRENDIZ_HECHICERO));
        profesiones.put(NomProf.ALGUACIL,new Profesion(NomProf.ALGUACIL));
        profesiones.put(NomProf.ARTISTA,new Profesion(NomProf.ARTISTA));
        profesiones.put(NomProf.AYUDANTE_CAMARA,new Profesion(NomProf.AYUDANTE_CAMARA));
        profesiones.put(NomProf.BARQUERO,new Profesion(NomProf.BARQUERO));
        profesiones.put(NomProf.BARBERO_CIRUJANO,new Profesion(NomProf.BARBERO_CIRUJANO));
        profesiones.put(NomProf.BATELERO,new Profesion(NomProf.BATELERO));
        profesiones.put(NomProf.BERSERKER,new Profesion(NomProf.BERSERKER));
        profesiones.put(NomProf.BURGUES,new Profesion(NomProf.BURGUES));
        profesiones.put(NomProf.BRIBON,new Profesion(NomProf.BRIBON));
        profesiones.put(NomProf.CAMPESINO,new Profesion(NomProf.CAMPESINO));
        profesiones.put(NomProf.CARBONERO,new Profesion(NomProf.CARBONERO));
        profesiones.put(NomProf.CAZADOR,new Profesion(NomProf.CAZADOR));
        profesiones.put(NomProf.CARCELERO,new Profesion(NomProf.CARCELERO));
        profesiones.put(NomProf.CAZARRATAS,new Profesion(NomProf.CAZARRATAS));
        profesiones.put(NomProf.CAZARRECOMPENSAS,new Profesion(NomProf.CAZARRECOMPENSAS));
        profesiones.put(NomProf.CONTRABANDISTA,new Profesion(NomProf.CONTRABANDISTA));
        profesiones.put(NomProf.COCHERO,new Profesion(NomProf.COCHERO));
        profesiones.put(NomProf.EMBAJADOR,new Profesion(NomProf.EMBAJADOR));
        profesiones.put(NomProf.ESCOLTA,new Profesion(NomProf.ESCOLTA));
        profesiones.put(NomProf.ESCUDERO,new Profesion(NomProf.ESCUDERO));
        profesiones.put(NomProf.ESCRIBA,new Profesion(NomProf.ESCRIBA));
        profesiones.put(NomProf.ESPADACHIN,new Profesion(NomProf.ESPADACHIN));
        profesiones.put(NomProf.ESTUDIANTE,new Profesion(NomProf.ESTUDIANTE));
        profesiones.put(NomProf.FORAJIDO,new Profesion(NomProf.FORAJIDO));
        profesiones.put(NomProf.FANATICO,new Profesion(NomProf.FANATICO));
        profesiones.put(NomProf.GLADIADOR,new Profesion(NomProf.GLADIADOR));
        profesiones.put(NomProf.GUERRERO_CAMARILLA,new Profesion(NomProf.GUERRERO_CAMARILLA));
        profesiones.put(NomProf.GUARDIA_MARINA,new Profesion(NomProf.GUARDIA_MARINA));
        profesiones.put(NomProf.GUARDAESPALDAS,new Profesion(NomProf.GUARDAESPALDAS));
        profesiones.put(NomProf.HECHICERO_VULGAR,new Profesion(NomProf.HECHICERO_VULGAR));
        profesiones.put(NomProf.INICIADO,new Profesion(NomProf.INICIADO));
        profesiones.put(NomProf.LADRON,new Profesion(NomProf.LADRON));
        profesiones.put(NomProf.KOSSAR,new Profesion(NomProf.KOSSAR));
        profesiones.put(NomProf.LADRON_TUMBAS,new Profesion(NomProf.LADRON_TUMBAS));
        profesiones.put(NomProf.LENADOR,new Profesion(NomProf.LENADOR));
        profesiones.put(NomProf.MATATROLLS,new Profesion(NomProf.MATATROLLS));
        profesiones.put(NomProf.MARINERO,new Profesion(NomProf.MARINERO));
        profesiones.put(NomProf.MATON,new Profesion(NomProf.MATON));
        profesiones.put(NomProf.MENESTRAL,new Profesion(NomProf.MENESTRAL));
        profesiones.put(NomProf.MERCENARIO,new Profesion(NomProf.MERCENARIO));
        profesiones.put(NomProf.MENSAJERO,new Profesion(NomProf.MENSAJERO));
        profesiones.put(NomProf.MIEMBRO_SEQUITO,new Profesion(NomProf.MIEMBRO_SEQUITO));
        profesiones.put(NomProf.MILICIANO,new Profesion(NomProf.MILICIANO));
        profesiones.put(NomProf.NOBLE,new Profesion(NomProf.NOBLE));
        profesiones.put(NomProf.MINERO,new Profesion(NomProf.MINERO));
        profesiones.put(NomProf.OSAMENTERO,new Profesion(NomProf.OSAMENTERO));
        profesiones.put(NomProf.PATRULLA_CAMINOS,new Profesion(NomProf.PATRULLA_CAMINOS));
        profesiones.put(NomProf.PEAJERO,new Profesion(NomProf.PEAJERO));
        profesiones.put(NomProf.PATRULLA_FRONTERIZA,new Profesion(NomProf.PATRULLA_FRONTERIZA));
        profesiones.put(NomProf.PESCADOR,new Profesion(NomProf.PESCADOR));
        profesiones.put(NomProf.PORTADOR_RUNAS,new Profesion(NomProf.PORTADOR_RUNAS));
        profesiones.put(NomProf.SAQUEADOR_TUMBAS,new Profesion(NomProf.SAQUEADOR_TUMBAS));
        profesiones.put(NomProf.ROMPESCUDO,new Profesion(NomProf.ROMPESCUDO));
        profesiones.put(NomProf.SICARIO,new Profesion(NomProf.SICARIO));
        profesiones.put(NomProf.SIRVIENTE,new Profesion(NomProf.SIRVIENTE));
        profesiones.put(NomProf.VAGABUNDO,new Profesion(NomProf.VAGABUNDO));
        profesiones.put(NomProf.SOLDADO,new Profesion(NomProf.SOLDADO));
        profesiones.put(NomProf.VIGILANTE,new Profesion(NomProf.VIGILANTE));
        profesiones.put(NomProf.ARTESANO,new Profesion(NomProf.ARTESANO));
        profesiones.put(NomProf.ADMINISTRADOR,new Profesion(NomProf.ADMINISTRADOR));
        profesiones.put(NomProf.ASESINO,new Profesion(NomProf.ASESINO));
        profesiones.put(NomProf.BATIDOR,new Profesion(NomProf.BATIDOR));
        profesiones.put(NomProf.CABALLERO_INTERIOR,new Profesion(NomProf.CABALLERO_INTERIOR));
        profesiones.put(NomProf.CABALLERO,new Profesion(NomProf.CABALLERO));
        profesiones.put(NomProf.CAMPEON_JUDICIAL,new Profesion(NomProf.CAMPEON_JUDICIAL));
        profesiones.put(NomProf.CAPITAN,new Profesion(NomProf.CAPITAN));
        profesiones.put(NomProf.CAZADOR_BRUJAS,new Profesion(NomProf.CAZADOR_BRUJAS));
        profesiones.put(NomProf.CAPITAN_BARCO,new Profesion(NomProf.CAPITAN_BARCO));
        profesiones.put(NomProf.CAZADOR_INVISIBLE,new Profesion(NomProf.CAZADOR_INVISIBLE));
        profesiones.put(NomProf.CAZAVAMPIROS,new Profesion(NomProf.CAZAVAMPIROS));
        profesiones.put(NomProf.CORTESANO,new Profesion(NomProf.CORTESANO));
        profesiones.put(NomProf.CHARLATAN,new Profesion(NomProf.CHARLATAN));
        profesiones.put(NomProf.DEMAGOGO,new Profesion(NomProf.DEMAGOGO));
        profesiones.put(NomProf.DUELISTA,new Profesion(NomProf.DUELISTA));
        profesiones.put(NomProf.ESPIA,new Profesion(NomProf.ESPIA));
        profesiones.put(NomProf.ERUDITO,new Profesion(NomProf.ERUDITO));
        profesiones.put(NomProf.EXPLORADOR,new Profesion(NomProf.EXPLORADOR));
        profesiones.put(NomProf.EXTORSIONADOR,new Profesion(NomProf.EXTORSIONADOR));
        profesiones.put(NomProf.FRAILE,new Profesion(NomProf.FRAILE));
        profesiones.put(NomProf.FLAGELANTE,new Profesion(NomProf.FLAGELANTE));
        profesiones.put(NomProf.GALENO,new Profesion(NomProf.GALENO));
        profesiones.put(NomProf.GRAN_HECHICERO,new Profesion(NomProf.GRAN_HECHICERO));
        profesiones.put(NomProf.HECHICERO_MAESTRO,new Profesion(NomProf.HECHICERO_MAESTRO));
        profesiones.put(NomProf.HECHICERO_ADEPTO,new Profesion(NomProf.HECHICERO_ADEPTO));
        profesiones.put(NomProf.HERALDO,new Profesion(NomProf.HERALDO));
        profesiones.put(NomProf.HEROE,new Profesion(NomProf.HEROE));
        profesiones.put(NomProf.INGENIERO,new Profesion(NomProf.INGENIERO));
        profesiones.put(NomProf.HERRERUELO,new Profesion(NomProf.HERRERUELO));
        profesiones.put(NomProf.INTERROGADOR,new Profesion(NomProf.INTERROGADOR));
        profesiones.put(NomProf.JEFE_FORAJIDOS,new Profesion(NomProf.JEFE_FORAJIDOS));
        profesiones.put(NomProf.LADRON_GUANTE_BLANCO,new Profesion(NomProf.LADRON_GUANTE_BLANCO));
        profesiones.put(NomProf.JUGLAR,new Profesion(NomProf.JUGLAR));
        profesiones.put(NomProf.LADRON_EXPERTO,new Profesion(NomProf.LADRON_EXPERTO));
        profesiones.put(NomProf.MAESTRO_GREMIO,new Profesion(NomProf.MAESTRO_GREMIO));
        profesiones.put(NomProf.MATAGIGANTES,new Profesion(NomProf.MATAGIGANTES));
        profesiones.put(NomProf.MATADEMONIOS,new Profesion(NomProf.MATADEMONIOS));
        profesiones.put(NomProf.MERCADER,new Profesion(NomProf.MERCADER));
        profesiones.put(NomProf.NAVEGANTE,new Profesion(NomProf.NAVEGANTE));
        profesiones.put(NomProf.POLITICO,new Profesion(NomProf.POLITICO));
        profesiones.put(NomProf.PERISTA,new Profesion(NomProf.PERISTA));
        profesiones.put(NomProf.POSADERO,new Profesion(NomProf.POSADERO));
        profesiones.put(NomProf.SACERDOTE,new Profesion(NomProf.SACERDOTE));
        profesiones.put(NomProf.SALTEADOR_CAMINOS,new Profesion(NomProf.SALTEADOR_CAMINOS));
        profesiones.put(NomProf.SACERDOTE_UNGIDO,new Profesion(NomProf.SACERDOTE_UNGIDO));
        profesiones.put(NomProf.SARGENTO,new Profesion(NomProf.SARGENTO));
        profesiones.put(NomProf.SEGUNDO_BORDO,new Profesion(NomProf.SEGUNDO_BORDO));
        profesiones.put(NomProf.SENOR_NOBLE,new Profesion(NomProf.SENOR_NOBLE));
        profesiones.put(NomProf.SENOR_CRIMEN,new Profesion(NomProf.SENOR_CRIMEN));
        profesiones.put(NomProf.SUMO_SACERDOTE,new Profesion(NomProf.SUMO_SACERDOTE));
        profesiones.put(NomProf.TIRADOR,new Profesion(NomProf.TIRADOR));
        profesiones.put(NomProf.VETERANO,new Profesion(NomProf.VETERANO));
    }

    public static Diccionario getInstancia(){
        if(instancia == null){
            instancia = new Diccionario();
        }
        return instancia;
    }

    public HashMap<NomTal, Talento> getTalentos() {
        return talentos;
    }

    public HashMap<NomHab, Habilidad> getHabilidades() {
        return habilidades;
    }

    public HashMap<NomProf, Profesion> getProfesiones() {
        return profesiones;
    }
}

